### ISSUE TITLE
Faker deprecation warnings

### ISSUE THREAD

**Issue by ericatripp** [okitan/json_schema-faker#17]
We are getting the following deprecation warnings in our applications that require `json_schema_faker`

`.NOTE: Faker::Internet.safe_email is deprecated; use email instead. It will be removed on or after 2023-10.`

Looks like it's a simple method replacement needed here: https://github.com/okitan/json_schema-faker/blob/fbf52c2eaaee3bf7aeb68e51072624bf38707e97/lib/json_schema/faker/formats.rb#L19

**Comment by okitan** [comment]
released 0.6.3
