### ISSUE TITLE
undefined method `parse' for JsonSchema::Schema

### ISSUE THREAD

**Issue by epaillous** [okitan/json_schema-faker#4]
Hello

I just tried to use the simple example. I get this error : 
undefined method `parse' for JsonSchema::Schema:Class Did you mean? parent

Could you help me please ? :)

**Comment by epaillous** [comment]
I tried with 
schema = JsonSchema.parse!(raw_schema)
and it seems to work
But if I use it with a different schema, such as : 

`{
  "title": "fou",
  "type": "object",
  "properties": {
    "fou": {
      "type": "object",
      "properties": {
        "from": {
          "type": "string"
        },
        "to": {
          "type": "string"
        }
      },
      "required": [
        "from",
        "to"
      ]
    }
  },
  "required": [
    "fou"
  ]
}`


I get this : 

`{
absencetypeforexchange: {
from: "",
to: ""
}
}`

But i was waiting for some values in from and to. Is it possible to have like random string values ?

**Comment by okitan** [comment]
@epaillous 

> I tried with
schema = JsonSchema.parse!(raw_schema)
and it seems to work

Nice Catch! I've fixed README.md.

> Is it possible to have like random string values ?

I'm sorry `json_schema-faker` has no capability to generate random value.
Default Strategy `JsonSchema::Faker::Strategy::Simple` only generates least properties with least values.(for `"type": "string"` it just generates `"a" * minLength`)
But your patches welcome!

I'm going to create `JsonSchema::Faker::Strategy::Random` in the near future, but I cannot promise the timing.

Thanks!
